TinyCRM/TinyCrm.Web/Models/ErrorViewModel.cs
using System;

namespace TinyCrm.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TinyCRM/TinyCrm.Web/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TinyCrm.Core.Model;

namespace TinyCrm.Web.Models
{
    public class HomeViewModel
    {
        public List<Customer> Customers { get; set; }
        public List<Product> Products { get; set; }
    }
}

TinyCRM/TinyCrm.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinyCrm.Core.Data;
using TinyCrm.Core.Model;
using TinyCrm.Core.Services;
using TinyCrm.Core.Services.Options;

namespace TinyCrm.Web.Controllers
{
    [Route("customer")]
    public class CustomerController : Controller
    {
        private ICustomerService customerService;
        public CustomerController(ICustomerService cService)
        {
            customerService = cService;
        }

        [HttpPost]
        public IActionResult Create([FromBody] CreateCustomerOptions options)
        {
            var result = customerService.CreateCustomer(options);

            if (!result.Success){
                return StatusCode((int)result.ErrorCode, result.ErrorText);
            }

            return Json(result.Data);
        }


        [HttpGet("index")]
        public IActionResult Index()
        {
            var customerList = customerService
                .SearchCustomer(new CustomerSearchOptions())
                .ToList();

            return View(customerList);
        }

        [HttpGet("{id}/edit")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var customer = customerService.SearchCustomer(new CustomerSearchOptions()
            {
                CustomerId = id
            }).SingleOrDefault();

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        [HttpGet("{id}")]
        public IActionResult GetById(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var customer = customerService.SearchCustomer(new CustomerSearchOptions()
            {
                CustomerId = id
            }).SingleOrDefault();

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        [HttpPatch("{id}")]
        public IActionResult Update(int id,[FromBody] CustomerUpdateOptions options)
        {
            var result = customerService.UpdateCustomer(options,id);

            if (!result.Success)
            {
                return StatusCode((int)result.ErrorCode, result.ErrorText);
            }

            return Ok();
        }

        [HttpDelete("{id}")]
        public IActionResult DeleteCustomer(int id)
        {
            var result = customerService.DeleteCustomerById(id);

            if (!result.Success)
            {
                return StatusCode((int)result.ErrorCode, result.ErrorText);
            }

            return Ok();
        }

        [HttpGet]
        public IActionResult Search(CustomerSearchOptions options)
        {
            if (options == null)
            {
                return BadRequest();
            }

            var customers = customerService
                .SearchCustomer(options)
                .ToList();

            if (customers == null)
            {
                return NotFound();
            }

            return Json(customers);
        }
    }
}

TinyCRM/TinyCrm.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TinyCrm.Core.Data;
using TinyCrm.Core.Services;
using TinyCrm.Core.Services.Options;
using TinyCrm.Web.Models;

namespace TinyCrm.Web.Controllers
{
    public class HomeController : Controller
    {
        private TinyCrmDbContext dbContext;
        private ICustomerService customerService;
        private IProductService productService;

        public HomeController(ICustomerService cService,IProductService pService,TinyCrmDbContext context)
        {
            customerService = cService;
            productService = pService;
            dbContext = context;
        }

        public IActionResult Index()
        {
            var model = new HomeViewModel();

            model.Customers = customerService.SearchCustomer(
                new CustomerSearchOptions())
                .ToList(); 

            model.Products = productService.SearchProduct(new ProductSearchOptions())
                .ToList();
            
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }


        public IActionResult AddProduct()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TinyCRM/TinyCrm.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinyCrm.Core.Model;
using TinyCrm.Core.Services;
using TinyCrm.Core.Services.Options;

namespace TinyCrm.Web.Controllers
{
    [Route("product")]
    public class ProductController : Controller
    {
        private IProductService productService; 
        public ProductController(IProductService pService)
        {
            productService = pService;
        }
        [HttpGet("index")]
        public IActionResult Index()
        {
            return View(productService.SearchProduct(new ProductSearchOptions()).ToList());
        }

        [HttpPost]
        public Product AddProduct ([FromBody] CreateProductOptions options)
        {
            return productService.CreateProduct(options);
        }
    }
}

TinyCRM/TinyCrm.Web/Views/Customer/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model TinyCrm.Core.Model.Customer



<form method="post">
    <h2>Edit info</h2>
    <div class="form-group">
        <label for="InputFirstName">First Name</label>
        <input type="text" value="@Model.Firstname" class="form-control" name="FirstName">
        <label for="InputLastName">Last Name</label>
        <input type="text" value="@Model.Lastname" class="form-control" name="LastName">
        <label for="InputVatNumber">Vat Number</label>
        <input type="number" value="@Model.VatNumber" class="form-control" name="VatNumber">
        <label for="InputPhone">Phone</label>
        <input type="number" value="@Model.Phone" class="form-control" name="Phone">
        <label for="InputEmail">Email address</label>
        <input type="email" value="@Model.Email" class="form-control" name="Email" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TinyCRM/TinyCrm.Web/Views/Customer/GetById.cshtml
@model TinyCrm.Core.Model.Customer

@{
    ViewData["Title"] = "GetById";
}

@if (Model == null)
{
    <div class="alert alert-warning" role="alert">
        Customer not found
    </div>
    return;
}
<div class="card">
    <div class="card-header">
        @Model.Firstname @Model.Lastname
    </div>
    <div class="card-body">
        <h5 class="card-title">@Model.VatNumber</h5>
        <p class="card-text">Phone: @Model.Phone</p>
        <p class="card-text">Is Active: @Model.IsActive</p>
        <a class="btn btn-primary" href="@Url.Action("Edit", "Customer", new {id = Model.CustomerId })">Edit</a>
    </div>
</div>

TinyCRM/TinyCrm.Web/Views/Customer/Index.cshtml
@using TinyCrm.Core.Model
@{
    ViewData["Title"] = "Home Page";
}

@model List<Customer>


<h2 class="display-4">Customers</h2>

<table class="table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Vat Number</th>
            <th scope="col">Gross</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model)
        {
            <tr>
                <th scope="row">@c.CustomerId</th>
                <td>@c.Firstname</td>
                <td>@c.Lastname</td>
                <td>@c.VatNumber</td>
                <td>@c.TotalGross</td>
                <td><a class="nav-link" href="@Url.Action("GetById", "Customer", new {id = c.CustomerId })">Details</a></td>
            </tr>
        }
    </tbody>
</table>
<h5>Total Customers: @Model.Count()</h5>

TinyCRM/TinyCrm.Web/Views/Home/AddProduct.cshtml
@{
    ViewData["Title"] = "AddProduct";
}

<h1>AddProduct</h1>

<form>
    <table>
        <tr><td>Id</td><td><input type="text" id="ProductId" name="ProductId" /></td></tr>
        <tr><td>Name</td><td><input type="text" id="Name" name="Name" /></td></tr>
        <tr><td>Description</td><td><input type="text" id="Description" name="Description" /></td></tr>
        <tr><td>Price</td><td><input type="number" step="0.01" min="0" id="Price" name="Price" /></td></tr>
        <tr>
            <td>
                <input type="button" onclick="addProductToServer()" value="Submit" />
            </td>
        </tr>
    </table>
</form>

<div id="responseDiv"> </div>

TinyCRM/TinyCrm.Web/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<h2>Customers</h2>
<table class="table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Vat Number</th>
            <th scope="col">Gross</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model.Customers)
        {
            <tr>
                <th scope="row">@c.CustomerId</th>
                <td>@c.Firstname</td>
                <td>@c.Lastname</td>
                <td>@c.VatNumber</td>
                <td>@c.TotalGross</td>
                <td><a class="nav-link" href="@Url.Action("GetById", "Customer", new {id = c.CustomerId })">Details</a></td>
            </tr>
        }
    </tbody>
</table>
<h5>TotalCustomers: @Model.Customers.Count()</h5>

<h2>Products</h2>
<table class="table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model.Products)
        {
            <tr>
                <th scope="row">@c.ProductId</th>
                <td>@c.Name</td>
                <td>@c.Price</td>
            </tr>
        }
    </tbody>
</table>
<h5>TotalProducts: @Model.Products.Count()</h5>

TinyCRM/TinyCrm.Web/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model List<TinyCrm.Core.Model.Product>


<h2 class="display-4">Products</h2>

<table class="table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model)
        {
            <tr>
                <th scope="row">@c.ProductId</th>
                <td>@c.Name</td>
                <td>@c.Price</td>
            </tr>
        }
    </tbody>
</table>
<h5>Total Products: @Model.Count()</h5>

TinyCRM/TinyCrm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TinyCrm.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TinyCrm.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddProduct">AddProduct</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TinyCrm.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>